### ISSUE TITLE
Definitions for input files

### ISSUE THREAD

**Issue by brwnj** [hallamlab/LCAStar#1]
Is there any chance you could define the columns of the input files:

```
blast_results/refseq.*.parsed.txt
```

Above and beyond would be explaining how you came to those values (maybe even separating out that code from `metapathways2` and adding it here).

I made an effort to go through `metapathways2` to find the answer, but things are not straightforward.

Edit: The input is also not outlined in your paper.

**Comment by Tony-xy-Liu** [comment]
as of ver2.0.0 (f0f4ac3ad0e8053844dd5ccc3b82729275e1cfb4) accepted inputs are now:
- ncbi taxonomy id
- scientific name (genus species)
- or a list of strings representing a path from the root node to the assigned node (which is agnostic to the tree being used)
